name: YouTube Article Update

on:
  workflow_dispatch:
  schedule:
    - cron: '16 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.GH_TOKEN }}  # GitHubアクセストークンをここで指定します
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install contentful
    - name: Fetch Latest YouTube Videos
      run: python fetch_videos.py
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    - name: Update README
      run: |
        # README.md の内容を一時ファイルにコピー
        cp README.md README.tmp
        # latest-videos.md の内容を挿入する位置を特定し、以前の投稿をクリアしてから内容を挿入
        awk '
          /<!-- latest-youtube-posts:start -->/ {
            print;                          # タグ行を出力
            system("cat latest-videos.md"); # latest-videos.md の内容を出力
            flag=1;                         # フラグを立てる
            next;                           # 次の行に進む
          }
          /<!-- latest-youtube-posts:end -->/ {
            print;                          # エンドタグ行を出力
            flag=0;                         # フラグを下ろす
          }
          !flag {                           # フラグが下がっている行だけを出力
            print
          }
        ' README.tmp > README.md
        # 一時ファイルを削除
        rm README.tmp
        git status
        git diff README.md
    - name: Commit and push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with latest YouTube videos"
        git push
