name: Blog and YouTube Article Update


on:
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.GH_TOKEN }} # GitHubアクセストークンをここで指定します
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install contentful
    - name: Fetch latest blog posts
      run: | 
        node fetch-post.js > latest-posts.md
        cat latest-posts.md
      env:
        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        CONTENTFUL_CONTENT_TYPE_ID: ${{ secrets.CONTENTFUL_CONTENT_TYPE_ID }}
    - name: Fetch Latest YouTube Videos
      run: python fetch_videos.py
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    - name: Update README
      run: |
        cat latest-videos.md
        # README.md の内容を一時ファイルにコピー
        cp README.md README.tmp
        # latest-posts.md の内容を挿入する位置を特定し、以前の投稿をクリアしてから内容を挿入
        awk '/<!-- latest-youtube-posts:start -->/{print; system("cat latest-videos.md"); flag=1; next} /<!-- latest-youtube-posts:end -->/{flag=0} !flag' README.tmp > README.md
        cat README.tmp | grep youtube
        cat latest-posts.md
        awk '/<!-- latest-posts:start -->/{print; system("cat latest-posts.md"); flag=1; next} /<!-- latest-posts:end -->/{flag=0} !flag' README.tmp > README.md
        cat README.tmp | grep posts
        # 一時ファイルを削除
        rm README.tmp
    - name: Commit and push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with latest blog posts"
        git push
